# SPDX-License-Identifier: MIT
name: Integration test

on:
  push:
    branches:
    - poc/kind-it

env:
  TASK_VERSION: 2.8.0

jobs:
  kind:
    runs-on: ubuntu-18.04
    steps:
    - name: Set up task
      run: |
        sudo bash -c 'curl -fsSL https://taskfile.dev/install.sh | bash -s -- -b /usr/local/bin v${{ env.TASK_VERSION }}'
    - name: Set up environment variables
      run: |
        echo "::set-env name=DOCKER_REGISTRY::$(echo -n 'docker.pkg.github.com/${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        task docker:build DOCKER_REGISTRY="${DOCKER_REGISTRY}"
        docker tag "${DOCKER_REGISTRY}/namespace-provisioner:latest" docker.pkg.github.com/daimler/namespace-provisioner/namespace-provisioner:latest
    - name: Set up kind
      uses: engineerd/setup-kind@v0.4.0
    - name: Run integration tests
      run: |
        kubectl cluster-info
        ./test/run-it.sh
